package rgc.pokedex;

import android.content.Intent;
import android.os.Bundle;
import android.support.v7.app.AppCompatActivity;
import android.view.View;
import android.view.Window;
import android.view.WindowManager;
import android.widget.AdapterView;
import android.widget.ListView;

import java.util.ArrayList;

/**
 * Created by Raúl on 15/10/2016.
 */
public class ListOfPokemon extends AppCompatActivity {
    private ListView pokemonListView;
    private ArrayList<Pokemon> pokes;
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        requestWindowFeature(Window.FEATURE_NO_TITLE);
        getWindow().setFlags(WindowManager.LayoutParams.FLAG_FULLSCREEN,
                WindowManager.LayoutParams.FLAG_FULLSCREEN);

        getSupportActionBar().hide();
        setContentView(R.layout.pokemon_list);
        pokes = new ArrayList<Pokemon>();
        loadPokemones();
        PokemonAdapter aP = new PokemonAdapter(this,pokes);
        pokemonListView = (ListView) findViewById(R.id.listView);
        pokemonListView.setAdapter(aP);

        pokemonListView.setOnItemClickListener(new AdapterView.OnItemClickListener() {
            @Override
            public void onItemClick(AdapterView<?> adapterView, View view, int i, long l) {
                Intent intent =new Intent(ListOfPokemon.this,PokemonShow.class);
                intent.putExtra("np", pokes.get(i).getNumPoke());
                intent.putExtra("n", pokes.get(i).getName());
                intent.putExtra("i", pokes.get(i).getImage());
                intent.putExtra("t1", pokes.get(i).getType1());
                intent.putExtra("t2", pokes.get(i).getType2());
                intent.putExtra("d", pokes.get(i).getDescription());
                startActivity(intent);
            }
        });

    }
    public void loadPokemones(){
       pokes.add(new Pokemon(R.drawable.ico1,"Bulbasaur",R.drawable.p001,1,"Planta","Veneno","A Bulbasaur es fácil verle echándose una siesta al sol. La semilla que tiene en el lomo va creciendo cada vez más a medida que absorbe los rayos del sol."));
        pokes.add(new Pokemon(R.drawable.ico2,"Ivysaur",R.drawable.p002,2,"Planta","Veneno","Este Pokémon lleva un bulbo en el lomo y, para poder con su peso, tiene unas patas y un tronco gruesos y fuertes. Si empieza a pasar más tiempo al sol, será porque el bulbo está a punto de hacerse una flor grande."));
        pokes.add(new Pokemon(R.drawable.ico3,"Venusaur",R.drawable.p003,3,"Planta","Veneno","Venusaur tiene una flor enorme en el lomo que, según parece, adquiere unos colores muy vivos si está bien nutrido y le da mucho el sol. El aroma delicado de la flor tiene un efecto relajante en el ánimo de las personas."));
        pokes.add(new Pokemon(R.drawable.ico4,"Charmander",R.drawable.p004,4,"Fuego","","La llama que tiene en la punta de la cola arde según sus sentimientos. Llamea levemente cuando está alegre y arde vigorosamente cuando está enfadado."));
        pokes.add(new Pokemon(R.drawable.ico5,"Charmeleon",R.drawable.p005,5,"Fuego","","Charmeleon no tiene reparo en acabar con su rival usando las afiladas garras que tiene. Si su enemigo es fuerte, se vuelve agresivo, y la llama que tiene en el extremo de la cola empieza a arder con mayor intensidad tornándose azulada"));
        pokes.add(new Pokemon(R.drawable.ico6,"Charizard",R.drawable.p006,6,"Fuego","Volador","Charizard se dedica a volar por los cielos en busca de oponentes fuertes. Echa fuego por la boca y es capaz de derretir cualquier cosa. No obstante, si su rival es más débil que él, no usará este ataque."));
        pokes.add(new Pokemon(R.drawable.ico7,"Squirtle",R.drawable.p007,7,"Agua","","El caparazón de Squirtle no le sirve de protección únicamente. Su forma redondeada y las hendiduras que tiene le ayudan a deslizarse en el agua y le permiten nadar a gran velocidad."));
        pokes.add(new Pokemon(R.drawable.ico8,"Wartortle",R.drawable.p008,8,"Agua","","Tiene una cola larga y cubierta de un pelo abundante y grueso que se torna más oscuro a medida que crece. Los arañazos que tiene en el caparazón dan fe de lo buen guerrero que es."));
        pokes.add(new Pokemon(R.drawable.ico9,"Blastoise",R.drawable.p009,9,"Agua","","Blastoise lanza chorros de agua con gran precisión por los tubos que le salen del caparazón que tiene en la espalda. Puede disparar chorros de agua con tanta puntería que no fallaría al tirar contra una lata pequeña a 50 m."));
        pokes.add(new Pokemon(R.drawable.ico10,"Caterpie",R.drawable.p010,10,"Bicho","","Caterpie tiene un apetito voraz. Es capaz de devorar hojas que superen su tamaño en un abrir y cerrar de ojos. Atención a la antena que tiene: libera un hedor realmente fuerte."));
        pokes.add(new Pokemon(R.drawable.ico11,"Metapod",R.drawable.p011,11,"Bicho","","La capa que recubre el cuerpo de este Pokémon es tan dura como una plancha de hierro. Metapod apenas se mueve. Permanece inmóvil para que las vísceras evolucionen dentro de la coraza que le rodea."));
        pokes.add(new Pokemon(R.drawable.ico12,"Butterfree",R.drawable.p012,12,"Bicho","Volador","Butterfree tiene una habilidad especial para encontrar delicioso polen en las flores. Puede localizar, extraer y transportar polen de flores que estén floreciendo a 10 km de distancia de su nido."));
        pokes.add(new Pokemon(R.drawable.ico13,"Weedle",R.drawable.p013,13,"Bicho","Veneno","Weedle tiene un finísimo sentido del olfato. Es capaz de distinguir las hojas que le gustan de las que no le gustan olisqueando un poco con la gran nariz que tiene."));
        pokes.add(new Pokemon(R.drawable.ico14,"Kakuna",R.drawable.p014,14,"Bicho","Veneno","Kakuna permanece prácticamente inmóvil al encaramarse a los árboles, aunque la actividad interna de su organismo tiene un ritmo frenético, pues se prepara para su evolución. Prueba de esto es la alta temperatura de su caparazón."));
        pokes.add(new Pokemon(R.drawable.ico15,"Beedrill",R.drawable.p015,15,"Bicho","Veneno","Los Beedrill defienden su territorio a toda costa. No es conveniente acercarse a su colmena, por seguridad. Si se les molesta, todo un enjambre atacará ferozmente."));
        pokes.add(new Pokemon(R.drawable.ico16,"Pidgey",R.drawable.p016,16,"Normal","Volador","Pidgey tiene un sentido de la orientación muy desarrollado. Es capaz de regresar a su nido, por lejos que se encuentre de las zonas que le resultan familiares."));
        pokes.add(new Pokemon(R.drawable.ico17,"Pidgeotto",R.drawable.p017,17,"Normal","Volador","Pidgeotto se apodera de una zona muy vasta como su territorio y la sobrevuela para controlarla. Si alguien invade su espacio vital, no tendrá ningún reparo en castigarlo con sus afiladas garras."));
        pokes.add(new Pokemon(R.drawable.ico18,"Pidgeot",R.drawable.p018,18,"Normal","Volador","El plumaje de este Pokémon es bonito e hipnótico. Muchos Entrenadores se quedan embobados ante la belleza impactante de las plumas que tiene en la cabeza; lo que les lleva a elegir a Pidgeot como su Pokémon."));
        pokes.add(new Pokemon(R.drawable.ico19,"Rattata",R.drawable.p019,19,"Normal","","Rattata es cauto como él solo. Hasta cuando duerme mueve las orejas para oír todos los ruidos. No es nada delicado a la hora de elegir su hábitat. Cualquier sitio es bueno para cavar su madriguera."));
        pokes.add(new Pokemon(R.drawable.ico20,"Raticate",R.drawable.p020,20,"Normal","","A Raticate le crecen los incisivos firmes y fuertes. Para mantenerlos afilados roe troncos y rocas, e incluso las paredes de las casas."));
        pokes.add(new Pokemon(R.drawable.ico21,"Spearow",R.drawable.p021,21,"Normal","Volador","Spearow pía con tanta fuerza que se le puede oír a 1 km de distancia. Si al agudo chillido le sigue una especie de eco, estaremos oyendo la respuesta de otros Spearow que contestan ante el aviso de peligro."));
        pokes.add(new Pokemon(R.drawable.ico22,"Fearow",R.drawable.p022,22,"Normal","Volador","A Fearow se le reconoce por tener un pescuezo y un pico largos que le permiten cazar en tierra y agua. Tiene una gran habilidad moviendo el fino pico para atrapar a sus presas."));
        pokes.add(new Pokemon(R.drawable.ico23,"Ekans",R.drawable.p023,23,"Veneno","","Ekans se enrosca para descansar. Adoptando esta posición puede responder rápidamente a cualquier amenaza que le aceche desde cualquier lugar, levantando la cabeza con una feroz mirada."));
        pokes.add(new Pokemon(R.drawable.ico24,"Arbok",R.drawable.p024,24,"Veneno","","Este Pokémon es tremendamente fuerte, puede oprimir cualquier cosa con su cuerpo y hasta es capaz de estrujar un barril de acero. Una vez que Arbok se enrosca a su víctima, no hay forma de escapar de su asfixiante abrazo."));
        pokes.add(new Pokemon(R.drawable.ico25,"Pikachu",R.drawable.p025,25,"Eléctrico","","Cada vez que un Pikachu se encuentra con algo nuevo, le lanza una descarga eléctrica. Cuando se ve alguna baya chamuscada, es muy probable que sea obra de un Pikachu, ya que a veces no controlan la intensidad de la descarga."));
        pokes.add(new Pokemon(R.drawable.ico26,"Raichu",R.drawable.p026,26,"Eléctrico","","Si las bolsas de los mofletes se le cargan demasiado, Raichu planta la cola en el suelo para liberar electricidad. Es común encontrar zonas chamuscadas cerca de la madriguera de este Pokémon."));
        pokes.add(new Pokemon(R.drawable.ico27,"Sandshrew",R.drawable.p027,27,"Tierra","","Sandshrew es capaz de absorber agua y no perder ni una gota, algo que le permite sobrevivir en el desierto. Este Pokémon se enrosca para defenderse de los enemigos."));
        pokes.add(new Pokemon(R.drawable.ico28,"Sandslash",R.drawable.p028,28,"Tierra","","Sandslash está recubierto de duras púas que son partes endurecidas de la piel. Suele mudarlas una vez al año; debajo de las viejas púas crecen unas nuevas que las sustituyen."));
        pokes.add(new Pokemon(R.drawable.ico29,"Nidoran♀",R.drawable.p029,29,"Veneno","","Nidoran♀ tiene púas que segregan un veneno muy potente. Se piensa que las desarrolló como protección del cuerpo tan pequeño que tiene. Cuando se enfada, libera una horrible sustancia tóxica por el cuerno."));
        pokes.add(new Pokemon(R.drawable.ico30,"Nidorina",R.drawable.p030,30,"Veneno","","Cuando están en familia o con sus amigos, esconden las púas para evitar accidentes. Según parece, se alteran bastante si se separan del grupo."));
        pokes.add(new Pokemon(R.drawable.ico31,"Nidoqueen",R.drawable.p031,31,"Veneno","Tierra","Nidoqueen tiene el cuerpo totalmente recubierto de escamas durísimas. Suele lanzar por los aires a sus rivales de los violentos golpes que les propina. Cuando se trata de defender a sus crías, alcanza su nivel máximo de fuerza."));
        pokes.add(new Pokemon(R.drawable.ico32,"Nidoran♂",R.drawable.p032,32,"Veneno","","Nidoran♂ ha desarrollado músculos para mover las orejas y orientarlas en cualquier dirección. De este modo, es capaz de captar hasta el sonido más leve."));
        pokes.add(new Pokemon(R.drawable.ico33,"Nidorino",R.drawable.p033,33,"Veneno","","Nidorino tiene un cuerno de dureza superior a la del diamante. Si siente una presencia hostil, se le erizan las púas del lomo enseguida y carga contra el enemigo con todas sus fuerzas."));
        pokes.add(new Pokemon(R.drawable.ico34,"Nidoking",R.drawable.p034,34,"Veneno","Tierra","La gruesa cola de Nidoking encierra una fuerza realmente destructora. Con una vez que la agite, es capaz de tumbar una torre metálica de transmisión. Una vez que este Pokémon se desboca, no hay quien lo pare."));
        pokes.add(new Pokemon(R.drawable.ico35,"Clefairy",R.drawable.p035,35,"Hada","","Siempre que hay luna llena, salen en grupo para jugar. Al amanecer, los Clefairy, agotados, regresan a sus refugios de montaña para dormir acurrucados unos con otros."));
        pokes.add(new Pokemon(R.drawable.ico36,"Clefable",R.drawable.p036,36,"Hada","","Clefable se mueve dando saltitos como si fuera haciendo uso de las alas. Estos pequeños brincos le permiten caminar por el agua. De todos es sabido que le encanta darse paseos por los lagos en tranquilas noches de luna llena."));
        pokes.add(new Pokemon(R.drawable.ico37,"Vulpix",R.drawable.p037,37,"Fuego","","Al nacer, Vulpix tiene una cola blanca que se divide en seis si recibe cariño por parte de su Entrenador. Las seis colas se le rizan de forma majestuosa."));
        pokes.add(new Pokemon(R.drawable.ico38,"Ninetales",R.drawable.p038,38,"Fuego","","Ninetales emite una siniestra luz a través de los brillantes ojos rojos que tiene, para conseguir controlar del todo la mente de su rival. Dicen que este Pokémon llega a vivir mil años."));
        pokes.add(new Pokemon(R.drawable.ico39,"Jigglypuff",R.drawable.p039,39,"Normal","Hada","Jigglypuff tiene unas cuerdas vocales que ajustan sin problema la longitud de onda de su voz. Este Pokémon usa la habilidad que tiene para cantar con la longitud de onda necesaria para adormecer a su rival."));
        pokes.add(new Pokemon(R.drawable.ico40,"Wigglytuff",R.drawable.p040,40,"Normal","Hada","Wigglytuff tiene unos ojos enormes con forma de platillo, que siempre están cubiertos de lágrimas. Si se le metiera algo en el ojo, enseguida se le saldría solo."));
        pokes.add(new Pokemon(R.drawable.ico41,"Zubat",R.drawable.p041,41,"Veneno","Volador","Durante el día, Zubat permanece inmóvil y a oscuras. Si este Pokémon pasara mucho tiempo expuesto al sol, correría el peligro de sufrir quemaduras."));
        pokes.add(new Pokemon(R.drawable.ico42,"Golbat",R.drawable.p042,42,"Veneno","Volador","A Golbat le encanta chuparles la sangre a los seres vivos. Este Pokémon es más activo en la oscuridad de la noche. Es al caer la noche cuando sale a revolotear y a buscar sangre fresca."));
        pokes.add(new Pokemon(R.drawable.ico43,"Oddish",R.drawable.p043,43,"Planta","Veneno","Durante el día, Oddish se entierra en el suelo para absorber nutrientes valiéndose de todo el cuerpo. Cuanto más fértil sea el suelo, mayor brillo tendrá en las hojas."));
        pokes.add(new Pokemon(R.drawable.ico44,"Gloom",R.drawable.p044,44,"Planta","Veneno","Gloom libera un fétido olor por el pistilo de la flor. Cuando está en peligro, el hedor se intensifica. Si este Pokémon está tranquilo y no se siente amenazado, no libera el desagradable olor."));
        pokes.add(new Pokemon(R.drawable.ico45,"Vileplume",R.drawable.p045,45,"Planta","Veneno","El polen que contienen las esporas tóxicas de Vileplume causa unos ataques de alergia muy agudos. Por eso, no es aconsejable acercarse a ninguna flor selvática, por muy bonita que sea."));
        pokes.add(new Pokemon(R.drawable.ico46,"Paras",R.drawable.p046,46,"Bicho","Planta","Paras lleva dos setas parásitas a cuestas llamadas tochukaso. Estas crecen alimentándose de los nutrientes de este Pokémon de tipo Bicho y Planta que les sirve de huésped. Las setas se usan como elixir de vida."));
        pokes.add(new Pokemon(R.drawable.ico47,"Parasect",R.drawable.p047,47,"Bicho","Planta","Parasect es conocido por destruir en plaga grandes árboles, absorbiendo los nutrientes que tienen en la parte baja del tronco y las raíces. Cuando un árbol azotado por la plaga muere, los Parasect van a por el siguiente al instante."));
        pokes.add(new Pokemon(R.drawable.ico48,"Venonat",R.drawable.p048,48,"Bicho","Veneno","Dicen que durante su evolución Venonat desarrolló una fina capa de espeso pelo alrededor de todo el cuerpo para protegerse. Tiene unos ojos tan grandes que no hay presa que le pase desapercibida."));
        pokes.add(new Pokemon(R.drawable.ico49,"Venomoth",R.drawable.p049,49,"Bicho","Veneno","Venomoth es nocturno, solo actúa en la oscuridad. Su alimento preferido son los pequeños insectos que se concentran cerca de los focos de luz en la oscuridad de la noche."));
        pokes.add(new Pokemon(R.drawable.ico50,"Diglett",R.drawable.p050,50,"Tierra","","En la mayoría de las granjas se suelen criar Diglett por la sencilla razón de que, excaven donde excaven, dejan la tierra perfectamente labrada para sembrar. El terreno queda listo para plantar ricas verduras."));
        pokes.add(new Pokemon(R.drawable.ico51,"Dugtrio",R.drawable.p051,51,"Tierra","","Los Dugtrio son trillizos que se originaron a partir de un solo cuerpo, por eso piensan de la misma forma. A la hora de excavar, trabajan en equipo y sin descanso."));
        pokes.add(new Pokemon(R.drawable.ico52,"Meowth",R.drawable.p052,52,"Normal","","Meowth retrae las afiladas uñas de sus zarpas para caminar a hurtadillas, dando sigilosos pasos para pasar inadvertido. No se sabe muy bien por qué, pero este Pokémon adora las monedas brillantes que resplandecen con la luz."));
        pokes.add(new Pokemon(R.drawable.ico53,"Persian",R.drawable.p053,53,"Normal","","Persian tiene seis llamativos bigotes que le dan un aspecto feroz. Además, le sirven para detectar el movimiento del aire, delator de la presencia cercana de algún Pokémon. Si se le agarra por los bigotes, se vuelve dócil."));
        pokes.add(new Pokemon(R.drawable.ico54,"Psyduck",R.drawable.p054,54,"Agua","","Psyduck tiene un extraño poder, que consiste en generar ondas cerebrales iguales a las que se generan cuando se está dormido. Este descubrimiento levantó una gran polémica entre eruditos."));
        pokes.add(new Pokemon(R.drawable.ico55,"Golduck",R.drawable.p055,55,"Agua","","Golduck alcanza una velocidad de vértigo gracias a las aletas palmípedas de las extremidades y a la forma aerodinámica de su cuerpo. Realmente, la velocidad de este Pokémon supera la de cualquier nadador."));
        pokes.add(new Pokemon(R.drawable.ico56,"Mankey",R.drawable.p056,56,"Lucha","","Cuando Mankey empieza a temblar y a respirar con más intensidad, seguro que va a enfadarse. Aunque prever su enfado no sirve de nada porque alcanza un estado de rabia tan rápido que no hay escapatoria."));
        pokes.add(new Pokemon(R.drawable.ico57,"Primeape",R.drawable.p057,57,"Lucha","","Cuando Primeape se enfada, se le acelera el ritmo cardíaco y se le fortalecen los músculos. Con todo, pierde en inteligencia."));
        pokes.add(new Pokemon(R.drawable.ico58,"Growlithe",R.drawable.p058,58,"Fuego","","Growlithe tiene un sentido del olfato excepcional y una memoria sensitiva tremenda, nunca olvida una esencia. Este Pokémon saca provecho de este don para identificar las sensaciones que tienen otros seres vivos."));
        pokes.add(new Pokemon(R.drawable.ico59,"Arcanine",R.drawable.p059,59,"Fuego","","Arcanine es conocido por lo veloz que es. Dicen que es capaz de correr 10 000 km en 24 horas. El fuego que arde con vigor en el interior de este Pokémon constituye su fuente de energía."));
        pokes.add(new Pokemon(R.drawable.ico60,"Poliwag",R.drawable.p060,60,"Agua","","Poliwag tiene una piel muy fina. Tanto que es posible entrever a través de la misma las vísceras en espiral que tiene. La piel, aunque fina, tiene la ventaja de ser flexible y hacer rebotar hasta los colmillos más afilados."));
        pokes.add(new Pokemon(R.drawable.ico61,"Poliwhirl",R.drawable.p061,61,"Agua","","La piel de Poliwhirl está siempre húmeda y lubricada con un fluido viscoso. Gracias a esta película resbaladiza, puede escapar de las garras del enemigo, resbalándosele de las zarpas en pleno combate."));
        pokes.add(new Pokemon(R.drawable.ico62,"Poliwrath",R.drawable.p062,62,"Agua","Lucha","Poliwrath tiene unos músculos fornidos y muy desarrollados, por lo que nunca se agota. Es tan fuerte e incansable que cruzar el océano a nado no le supone ningún esfuerzo."));
        pokes.add(new Pokemon(R.drawable.ico63,"Abra",R.drawable.p063,63,"Psíquico","","Abra duerme 18 horas al día, pero puede detectar a cualquier enemigo que se le acerque mientras duerme. En una situación así, usa Teletransporte para protegerse."));
        pokes.add(new Pokemon(R.drawable.ico64,"Kadabra",R.drawable.p064,64,"Psíquico","","Kadabra emite unas ondas alfa muy particulares que provocan dolores de cabeza a los demás. Solo aquellos que tengan gran poder mental podrán optar a ser Entrenador de este Pokémon."));
        pokes.add(new Pokemon(R.drawable.ico65,"Alakazam",R.drawable.p065,65,"Psíquico","","El cerebro de Alakazam nunca deja de crecer y por eso al cuello le cuesta sostener el peso de la cabeza. Este Pokémon usa sus poderes psicoquinéticos para mantener en alto la cabeza."));
        pokes.add(new Pokemon(R.drawable.ico66,"Machop",R.drawable.p066,66,"Lucha","","Gracias a su portentosa musculatura, Machop no se agota por mucho esfuerzo que haga. Este Pokémon es tan fuerte que puede derrotar a cien personas adultas de una sola vez."));
        pokes.add(new Pokemon(R.drawable.ico67,"Machoke",R.drawable.p067,67,"Lucha","","Los entrenados músculos de Machoke son tan fuertes como el acero. Este Pokémon es tan fuerte que puede levantar con un solo dedo a un luchador de sumo."));
        pokes.add(new Pokemon(R.drawable.ico68,"Machamp",R.drawable.p068,68,"Lucha","","Machamp es tan fuerte que puede derribar lo que quiera. Sin embargo, cuando tiene que realizar una tarea que requiere delicadeza y destreza, se le enredan los brazos. Este Pokémon pasa a la acción sin pensar."));
        pokes.add(new Pokemon(R.drawable.ico69,"Bellsprout",R.drawable.p069,69,"Planta","Veneno","Bellsprout tiene un cuerpo delgado y flexible que le permite inclinarse y balancearse para esquivar los ataques. Este Pokémon escupe por la boca un fluido corrosivo capaz de hacer que se derrita hasta el hierro."));
        pokes.add(new Pokemon(R.drawable.ico70,"Weepinbell",R.drawable.p070,70,"Planta","Veneno","Weepinbell tiene un gancho a modo de extremidad superior trasera, que usa por la noche para colgarse de una rama y echarse a dormir. Si se mueve mientras duerme, puede acabar en el suelo."));
        pokes.add(new Pokemon(R.drawable.ico71,"Victreebel",R.drawable.p071,71,"Planta","Veneno","Victreebel tiene una enredadera que le sale de la cabeza y que agita a modo de señuelo para atraer a sus presas y así engullirlas por sorpresa cuando estas se aproximan incautas."));
        pokes.add(new Pokemon(R.drawable.ico72,"Tentacool",R.drawable.p072,72,"Agua","Veneno","Tentacool está compuesto en su mayor parte por agua. Si se le saca del mar, se secará y se quedará acartonado. Si este Pokémon se deshidrata, hay que echarlo inmediatamente de vuelta al mar."));
        pokes.add(new Pokemon(R.drawable.ico73,"Tentacruel",R.drawable.p073,73,"Agua","Veneno","entacruel tiene unas enormes esferas rojas en la cabeza, que brillan antes de lanzar una descarga ultrasónica a lo que le rodea. Este estallido crea unas olas tremendas a su alrededor."));
        pokes.add(new Pokemon(R.drawable.ico74,"Geodude",R.drawable.p074,74,"Roca","Tierra","Cuanto más larga es la vida de Geodude, mayor es el desgaste y la erosión que sufre, y más redondeada la forma que va adquiriendo. Sin embargo, el corazón permanece siempre duro, rocoso y tosco."));
        pokes.add(new Pokemon(R.drawable.ico75,"Graveler",R.drawable.p075,75,"Roca","Tierra","Graveler crece alimentándose a base de piedras. Y, según parece, las prefiere cubiertas de musgo. Cada día se abre camino comiéndose una tonelada de rocas."));
        pokes.add(new Pokemon(R.drawable.ico76,"Golem",R.drawable.p076,76,"Roca","Tierra","Golem vive en las montañas. Si se produce un gran terremoto, estos Pokémon descienden rodando en masa por las laderas."));
        pokes.add(new Pokemon(R.drawable.ico77,"Ponyta",R.drawable.p077,77,"Fuego","","Al nacer, Ponyta es muy débil y apenas puede ponerse en pie. Con todo, se va haciendo más fuerte al tropezarse y caerse en su intento por seguir a sus progenitores."));
        pokes.add(new Pokemon(R.drawable.ico78,"Rapidash",R.drawable.p078,78,"Fuego","","A Rapidash se le suele ver trotando sin rumbo fijo por los campos y llanos. Cuando tiene que ir a algún sitio en concreto, se le aviva el fuego de las melenas y emprende el galope llameante llegando a los 240 km/h."));
        pokes.add(new Pokemon(R.drawable.ico79,"Slowpoke",R.drawable.p079,79,"Agua","Psíquico","Slowpoke usa la cola para atrapar a sus presas metiéndola bajo el agua en las riberas de los ríos. Con todo, es olvidadizo, se le puede pasar lo que estaba haciendo y quedarse días enteros holgazaneando en la orilla."));
        pokes.add(new Pokemon(R.drawable.ico80,"Slowbro",R.drawable.p080,80,"Agua","Psíquico","Slowbro lleva en la cola un Shellder enganchado, sujeto por los dientes. Como Slowbro no puede usar la cola para pescar, se mete en el agua de mala gana en busca de sus presas."));
        pokes.add(new Pokemon(R.drawable.ico81,"Magnemite",R.drawable.p081,81,"Eléctrico","Acero","Magnemite se engancha a las líneas de tensión para nutrirse de electricidad. Cuando se producen apagones en las casas, es aconsejable revisar el automático y comprobar que no hay Pokémon de este tipo colgados de la caja de fusibles."));
        pokes.add(new Pokemon(R.drawable.ico82,"Magneton",R.drawable.p082,82,"Eléctrico","Acero","Magneton emite una fuerte energía magnética que causa estragos en los instrumentos mecánicos. Por ello, en las ciudades se avisa con sirenas cuando hay concentraciones de estos Pokémon."));
        pokes.add(new Pokemon(R.drawable.ico83,"Farfetch'd",R.drawable.p083,83,"Normal","Volador","Al parecer, entre los puerros que suelen llevar los Farfetch'd, los hay mejores y peores. A estos Pokémon se les ha visto luchar entre ellos por los mejores puerros."));
        pokes.add(new Pokemon(R.drawable.ico84,"Doduo",R.drawable.p084,84,"Normal","Volador","Las dos cabezas de Doduo duermen de forma independiente, siempre por turnos. Mientras una duerme, la otra hace de centinela por si aparecen enemigos."));
        pokes.add(new Pokemon(R.drawable.ico85,"Dodrio",R.drawable.p085,85,"Normal","Volador","Según parece, las cabezas no son las únicas partes del cuerpo que tiene triplicadas. Dodrio también tiene tres corazones y tres pares de pulmones. Con esta constitución, puede correr largas distancias sin cansarse."));
        pokes.add(new Pokemon(R.drawable.ico86,"Seel",R.drawable.p086,86,"Agua","","Seel busca a sus presas en aguas heladas, bajo las capas de hielo. Cuando necesita respirar, abre un agujerito en el hielo con la afilada protuberancia que tiene encima de la cabeza."));
        pokes.add(new Pokemon(R.drawable.ico87,"Dewgong",R.drawable.p087,87,"Agua","Hielo","A Dewgong le encanta dormitar sobre la frialdad del hielo. Antiguamente, algún que otro marino lo confundió con una sirena al verlo dormido sobre un glaciar."));
        pokes.add(new Pokemon(R.drawable.ico88,"Grimer",R.drawable.p088,88,"Veneno","","El elástico cuerpo de lodo de Grimer le permite colarse por cualquier orificio, sea del tamaño que sea. Este Pokémon entra en los bajantes de las cloacas para beberse el agua sucia."));
        pokes.add(new Pokemon(R.drawable.ico89,"Muk",R.drawable.p089,89,"Veneno","","Muk emana por todo el cuerpo un fluido maloliente que obliga a taparse la nariz. Con solo una gota de la sustancia que exuda este Pokémon, se podría contaminar un estanque."));
        pokes.add(new Pokemon(R.drawable.ico90,"Shellder",R.drawable.p090,90,"Agua","","Por la noche, este Pokémon usa la ancha lengua que tiene para hacer un agujero en el fondo del mar y echarse a dormir. Mientras duerme, Shellder cierra la concha, pero deja la lengua por fuera."));
        pokes.add(new Pokemon(R.drawable.ico91,"Cloyster",R.drawable.p091,91,"Agua","Hielo","Cloyster es capaz de nadar por el mar. Su técnica consiste en tragar agua y expulsarla por el conducto que tiene en la parte trasera. Este mismo sistema es el que usa para lanzar los pinchos que tiene alrededor de la concha."));
        pokes.add(new Pokemon(R.drawable.ico92,"Gastly",R.drawable.p092,92,"Fantasma","Venano","Gastly está compuesto en gran medida de materia gaseosa. Cuando hay viento, el aire arrastra parte de esta materia y el Pokémon mengua. Suelen agruparse bajo los aleros de las casas para resguardarse del viento."));
        pokes.add(new Pokemon(R.drawable.ico93,"Haunter",R.drawable.p093,93,"Fantasma","Veneno","Haunter es un Pokémon peligroso. Si se ve alguno flotando en la oscuridad y haciendo señas, conviene no acercarse. Este Pokémon intentará robarle la energía a su presa a base de lametazos."));
        pokes.add(new Pokemon(R.drawable.ico94,"Gengar",R.drawable.p094,94,"Fantasma","Veneno","Si alguien ve que su sombra le adelanta de repente en una noche oscura, es muy probable que lo que esté viendo no sea su sombra, sino a un Gengar haciéndose pasar por la misma."));
        pokes.add(new Pokemon(R.drawable.ico95,"Onix",R.drawable.p095,95,"Roca","Tierra","Onix tiene un imán en el cerebro, que actúa como una brújula para no perder la orientación cuando está cavando túneles. A medida que crece, se le redondea y suaviza el cuerpo."));
        pokes.add(new Pokemon(R.drawable.ico96,"Drowzee",R.drawable.p096,96,"Psíquico","","Si a alguien le pica la nariz mientras duerme, seguro que es porque tiene a uno de estos Pokémon cerca de la almohada intentando sacarle los sueños por la nariz para comérselos."));
        pokes.add(new Pokemon(R.drawable.ico97,"Hypno",R.drawable.p097,97,"Psíquico","","Hypno lleva un péndulo en la mano. El balanceo y el brillo que tiene sumen al rival en un estado de hipnosis profundo. Mientras busca a su presa, saca brillo al péndulo."));
        pokes.add(new Pokemon(R.drawable.ico98,"Krabby",R.drawable.p098,98,"Agua","","Krabby vive en la playa, enterrado en agujeros en la arena. Cuando en las playas de arena fina escasea la comida, es común ver a estos Pokémon echando un pulso panza contra panza en defensa de su territorio."));
        pokes.add(new Pokemon(R.drawable.ico99,"Kingler",R.drawable.p099,99,"Agua","","Kingler tiene una pinza enorme y descomunal que usa agitándola en el aire para comunicarse con otros. Lo malo es que, al pesarle tanto, se cansa enseguida."));
        pokes.add(new Pokemon(R.drawable.ico100,"Voltorb",R.drawable.p100,100,"Eléctrico","","Voltorb fue visto por primera vez en una empresa encargada de comercializar Poké Balls. La conexión que existe entre aquella primera vez que se le vio y el hecho de que se parece mucho a una Poké Ball sigue siendo un misterio."));
        pokes.add(new Pokemon(R.drawable.ico101,"Electrode",R.drawable.p101,101,"Eléctrico","","Los Electrode se alimentan de la electricidad de la atmósfera. En días de tormenta con rayos, es fácil verlos explotando por todos lados tras haber consumido demasiada electricidad."));
        pokes.add(new Pokemon(R.drawable.ico102,"Exeggcute",R.drawable.p102,102,"Planta","Psíquico","Este Pokémon está compuesto de seis huevos que forman una tupida piña que va girando. Cuando se empiezan a resquebrajar las cáscaras, no hay duda de que Exeggcute está a punto de evolucionar."));
        pokes.add(new Pokemon(R.drawable.ico103,"Exeggutor",R.drawable.p103,103,"Planta","Psíquco","Exeggutor es originario del trópico. Cuando se expone a un sol intenso, le empiezan a crecer las cabezas. Hay quien dice que, cuando las cabezas caen al suelo, se unen para formar un Exeggcute."));
        pokes.add(new Pokemon(R.drawable.ico104,"Cubone",R.drawable.p104,104,"Tierra","","A Cubone le ahoga la pena porque no volverá a ver jamás a su madre. La luna le recuerda a veces a ella, y se pone a llorar. Los churretes que tiene en el cráneo que lleva puesto son debidos a las lágrimas que derrama."));
        pokes.add(new Pokemon(R.drawable.ico105,"Marowak",R.drawable.p105,105,"Tierra","","Marowak es la forma evolucionada de Cubone. Es más fuerte porque ha superado la pena por la pérdida de su madre. El ánimo de este Pokémon, ya curtido y fortalecido, no es muy fácil de alterar."));
        pokes.add(new Pokemon(R.drawable.ico106,"Hitmonlee",R.drawable.p106,106,"Lucha","","Hitmonlee tiene la facilidad de encoger y estirar las patas. Con extremidades tan flexibles, propina unas patadas demoledoras. Tras la lucha, se masajea las piernas y relaja los músculos para descansar."));
        pokes.add(new Pokemon(R.drawable.ico107,"Hitmonchan",R.drawable.p107,107,"Lucha","","Dicen que Hitmonchan tiene el mismo ímpetu que un boxeador entrenándose para un campeonato mundial. Este Pokémon tiene un espíritu indomable que nunca se doblega ante la adversidad."));
        pokes.add(new Pokemon(R.drawable.ico108,"Lickitung",R.drawable.p108,108,"Normal","","Dicen que Hitmonchan tiene el mismo ímpetu que un boxeador entrenándose para un campeonato mundial. Este Pokémon tiene un espíritu indomable que nunca se doblega ante la adversidad."));
        pokes.add(new Pokemon(R.drawable.ico109,"Koffing",R.drawable.p109,109,"Veneno","","Si Koffing se pone nervioso, aumenta el nivel de toxicidad de los gases que tiene y los expulsa por todo el cuerpo. También suele hincharse mucho hasta llegar a explotar."));
        pokes.add(new Pokemon(R.drawable.ico110,"Weezing",R.drawable.p110,110,"Veneno","","A Weezing le encantan los gases que emanan de los desperdicios que quedan en la cocina. Este Pokémon busca casas sucias y descuidadas para crear su hogar. De noche, cuando los habitantes de la casa duermen, va a por la basura."));
        pokes.add(new Pokemon(R.drawable.ico111,"Rhyhorn",R.drawable.p111,111,"Tierra","Roca","Rhyhorn corre en línea recta arrasando todo lo que encuentra en su camino. Aun estrellándose de cabeza contra un bloque de acero, no se vería afectado; a lo sumo, notaría algo de dolor al día siguiente."));
        pokes.add(new Pokemon(R.drawable.ico112,"Rhydon",R.drawable.p112,112,"Tierra","Roca","Rhydon tiene un cuerno capaz de horadar hasta un diamante en bruto y con una sacudida de la cola puede derribar un edificio. La piel de este Pokémon es muy fuerte; ni los disparos de un cañón le arañarían."));
        pokes.add(new Pokemon(R.drawable.ico113,"Chansey",R.drawable.p113,113,"Normal","","Rhydon tiene un cuerno capaz de horadar hasta un diamante en bruto y con una sacudida de la cola puede derribar un edificio. La piel de este Pokémon es muy fuerte; ni los disparos de un cañón le arañarían."));
        pokes.add(new Pokemon(R.drawable.ico114,"Tangela",R.drawable.p114,114,"Planta","","A Tangela se le desprenden los tentáculos con facilidad en cuanto se los agarras. Y no solo no le duele, sino que le resulta muy útil para escapar rápido. Además, al día siguiente le crecen otros."));
        pokes.add(new Pokemon(R.drawable.ico115,"Kangaskhan",R.drawable.p115,115,"Normal","","No es recomendable molestar ni intentar atrapar a crías de Kangaskhan mientras estén jugando, ya que seguro que su madre anda cerca y reaccionará con enfado y violencia."));
        pokes.add(new Pokemon(R.drawable.ico116,"Horsea",R.drawable.p116,116,"Agua","","Horsea come insectos pequeños y el musgo de las rocas. Si las corrientes del océano cobran fuerza, este Pokémon se anclará con la cola a rocas o corales para evitar que las aguas lo arrastren."));
        pokes.add(new Pokemon(R.drawable.ico117,"Seadra",R.drawable.p117,117,"Agua","","Seadra se echa a dormir tras abrirse un hueco entre las ramas de los corales. Los pescadores de coral suelen pincharse con las púas venenosas de estos Pokémon si no los ven."));
        pokes.add(new Pokemon(R.drawable.ico118,"Goldeen",R.drawable.p118,118,"Agua","","Goldeen es un bello Pokémon que mueve con elegancia las aletas en el agua. Con todo, no hay que bajar la guardia, en cualquier momento puede embestir con el cuerno."));
        pokes.add(new Pokemon(R.drawable.ico119,"Saeking",R.drawable.p119,119,"Agua","","En otoño, se ven ejemplares de Seaking macho danzando en las riberas de los ríos para cortejar a las hembras. En esta época, la coloración de este Pokémon alcanza sus niveles máximos de belleza."));
        pokes.add(new Pokemon(R.drawable.ico120,"Staryu",R.drawable.p120,120,"Agua","","Staryu posee un órgano central, conocido como su núcleo, que brilla con una luz roja. A finales de verano, pueden verse en la playa los núcleos de estos Pokémon brillando como las estrellas del cielo."));
        pokes.add(new Pokemon(R.drawable.ico121,"Starmie",R.drawable.p121,121,"Agua","Psíquico","La parte central de Starmie, el núcleo brillante, resplandece con siete colores distintos. Debido a su naturaleza luminosa, a este Pokémon se le ha dado el apelativo de la Gema del Mar."));
        pokes.add(new Pokemon(R.drawable.ico122,"Mr. Mine",R.drawable.p122,122,"Psíquico","Hada","Mr. Mime es un experto en pantomima. Con sus gestos y movimientos es capaz de convencer a sus espectadores de que algo existe, cuando en realidad no es así. Pero, cuando el público se lo cree, las ilusiones se hacen realidad."));
        pokes.add(new Pokemon(R.drawable.ico123,"Scyther",R.drawable.p123,123,"Bicho","Volador","Es espectacular ver lo rápido que es Scyther. Su increíble velocidad refuerza el efecto del par de guadañas que tiene en los brazos, que ya son de por sí contundentes; rebanan gruesos troncos de un tajo."));
        pokes.add(new Pokemon(R.drawable.ico124,"Jynx",R.drawable.p124,124,"Hielo","Psíquico","Jynx camina con ritmo, balanceándose y moviendo las caderas como si estuviera bailando. Realiza unos movimientos tan vistosos y atractivos que no hay quien pueda resistirse a mover las caderas."));
        pokes.add(new Pokemon(R.drawable.ico125,"Electabuzz",R.drawable.p125,125,"Eléctrico","","Al desatarse una tormenta, bandadas de estos Pokémon se enfrentan entre sí para ver quién alcanza antes sitios altos en los que suelan caer rayos. Hay ciudades que usan Electabuzz en lugar de pararrayos."));
        pokes.add(new Pokemon(R.drawable.ico126,"Magmar",R.drawable.p126,126,"Fuego","","Al luchar, Magmar expulsa violentas llamas por todo el cuerpo para intimidar a su rival. Estos estallidos de fuego crean ondas de calor que abrasan la hierba y los árboles que haya en las proximidades."));
        pokes.add(new Pokemon(R.drawable.ico127,"Pinsir",R.drawable.p127,127,"Bicho","","Pinsir es sorprendentemente fuerte. Puede agarrar con los cuernos a un rival que pese el doble que él y levantarlo por los aires. En zonas frías, los movimientos de este Pokémon se vuelven lentos."));
        pokes.add(new Pokemon(R.drawable.ico128,"Tauros",R.drawable.p128,128,"Normal","","Este Pokémon no está contento a menos que esté continuamente de aquí para allá. Si no hay rival que luche contra Tauros, se estampa contra árboles grandes para calmarse y los embiste para echarlos abajo."));
        pokes.add(new Pokemon(R.drawable.ico129,"Magikarp",R.drawable.p129,129,"Agua","","Magikarp es el triste ejemplo de un Pokémon capaz únicamente de saltar y salpicar. Esta conducta llevó a científicos a estudiarlo en profundidad."));
        pokes.add(new Pokemon(R.drawable.ico130,"Gyarados",R.drawable.p130,130,"Agua","Volador","Cuando Magikarp evoluciona y se convierte en Gyarados, sufre un cambio estructural en las células del cerebro. Dicen que esa transformación es la causa de la naturaleza violenta y salvaje de este Pokémon."));
        pokes.add(new Pokemon(R.drawable.ico131,"Lapras",R.drawable.p131,131,"Agua","Hielo","Por culpa de la gente, Lapras está casi en extinción. Dicen que, al anochecer, se pone a cantar quejicoso mientras busca a los miembros de su especie que puedan quedar."));
        pokes.add(new Pokemon(R.drawable.ico132,"Ditto",R.drawable.p132,132,"Normal","","Ditto reorganiza la estructura de sus células para adoptar otras formas. Pero, como intente transformarse en algo guiándose por los datos que tenga almacenados en la memoria, habrá detalles que se le escapen."));
        pokes.add(new Pokemon(R.drawable.ico133,"Eevee",R.drawable.p133,133,"Normal","","La configuración genética de Eevee le permite mutar y adaptarse enseguida a cualquier medio en el que viva. La evolución de este Pokémon suele ser posible gracias a las radiaciones emitidas por varias piedras."));
        pokes.add(new Pokemon(R.drawable.ico134,"Vaporeon",R.drawable.p134,134,"Agua","","Vaporeon sufrió una mutación repentina y desarrolló aletas y branquias que le permiten vivir bajo el agua. Asimismo, este Pokémon tiene la habilidad de controlar las aguas."));
        pokes.add(new Pokemon(R.drawable.ico135,"Jolteon",R.drawable.p135,135,"Eléctrico","","Las células de Jolteon generan un nivel bajo de electricidad, cuya intensidad aumenta con la electricidad estática que acumula en un pelaje formado por agujas cargadas de electricidad. Esta característica le permite lanzar rayos."));
        pokes.add(new Pokemon(R.drawable.ico136,"Flareon",R.drawable.p136,136,"Fuego","","La suavidad del pelaje de Flareon tiene una función clara: libera calor para que el Pokémon no se asfixie. La temperatura corporal de este Pokémon puede alcanzar los 900 °C."));
        pokes.add(new Pokemon(R.drawable.ico137,"Porygon",R.drawable.p137,137,"Normal","","Porygon es capaz de convertirse otra vez en datos informáticos y de entrar en el ciberespacio. Tiene protección anticopia, así que es imposible duplicarlo."));
        pokes.add(new Pokemon(R.drawable.ico138,"Omanyte",R.drawable.p138,138,"Roca","Agua","Omanyte es uno de esos Pokémon ancestrales que se extinguieron hace muchísimo tiempo y que la gente ha recuperado a partir de fósiles. Si un enemigo le ataca, se esconderá dentro de la dura concha que tiene."));
        pokes.add(new Pokemon(R.drawable.ico139,"Omastar",R.drawable.p139,139,"Roca","Agua","Omastar usa los tentáculos para atrapar a su presa. Se cree que el motivo de su extinción fue el tamaño y el peso que llegó a alcanzar la concha que lleva a cuestas, lo que le entorpeció y ralentizó los movimientos."));
        pokes.add(new Pokemon(R.drawable.ico140,"Kabuto",R.drawable.p140,140,"Roca","Agua","Kabuto es un Pokémon regenerado a partir de un fósil, aunque, en raras ocasiones, se han encontrado casos de ejemplares vivos en estado salvaje. En 300 millones de años, este Pokémon no ha cambiado en nada."));
        pokes.add(new Pokemon(R.drawable.ico141,"Kabutops",R.drawable.p141,141,"Roca","Agua","Hace mucho tiempo, Kabutops buceaba para atrapar a sus presas. Parece ser que en algún momento cambió de hábitat y se adaptó a vivir en tierra firme. La transformación que se aprecia en las patas y branquias así lo confirma."));
        pokes.add(new Pokemon(R.drawable.ico142,"Aerodactyl",R.drawable.p142,142,"Roca","Volador","Los orígenes de Aerodactyl datan de la era de los dinosaurios. Se regeneró a partir de material genético contenido en ámbar. Se supone que fue el amo de los cielos en épocas pasadas."));
        pokes.add(new Pokemon(R.drawable.ico143,"Snorlax",R.drawable.p143,143,"Normal","","Un día cualquiera en la vida de Snorlax consiste en comer y dormir. Es un Pokémon tan dócil que es fácil ver niños usando la gran panza que tiene como lugar de juegos."));
        pokes.add(new Pokemon(R.drawable.ico144,"Articuno",R.drawable.p144,144,"Hielo","Volador","Articuno es un Pokémon pájaro legendario que puede controlar el hielo. El batir de sus alas congela el aire. Dicen que consigue hacer que nieve cuando vuela."));
        pokes.add(new Pokemon(R.drawable.ico145,"Zapdos",R.drawable.p145,145,"Eléctrico","Volador","Zapdos es un Pokémon pájaro legendario que tiene la habilidad de controlar la electricidad. Suele vivir en nubarrones. Este Pokémon gana mucha fuerza si le alcanzan los rayos."));
        pokes.add(new Pokemon(R.drawable.ico146,"Moltres",R.drawable.p146,146,"Fuego","Volador","Moltres es un Pokémon pájaro legendario que tiene la habilidad de controlar el fuego. Dicen que, si resulta herido, se sumerge en el líquido magma de un volcán para arder y curarse."));
        pokes.add(new Pokemon(R.drawable.ico147,"Dratini",R.drawable.p147,147,"Dragón","","Dratini muda y se despoja de la vieja piel continuamente. Es algo que necesita hacer porque la energía que tiene en su interior no para de alcanzar niveles incontrolables."));
        pokes.add(new Pokemon(R.drawable.ico148,"Dragonair",R.drawable.p148,148,"Dragón","","Dragonair acumula grandes cantidades de energía dentro de sí. Dicen que altera el clima de la zona en la que está descargando energía a través de las esferas de cristal que tiene en el cuello y en la cola."));
        pokes.add(new Pokemon(R.drawable.ico149,"Dragonite",R.drawable.p149,149,"Dragón","Volador","Dragonite es capaz de dar la vuelta al mundo en solo 16 horas. Es un Pokémon de buen corazón que guía hasta tierra a los barcos que se encuentran perdidos en plena tormenta y a punto de zozobrar."));
        pokes.add(new Pokemon(R.drawable.ico150,"Mewtwo",R.drawable.p150,150,"Psíquico","","Mewtwo fue creado por manipulación genética. Pero, a pesar de que el hombre creó su cuerpo, dotar a Mewtwo de un corazón compasivo quedó en el olvido."));
        pokes.add(new Pokemon(R.drawable.ico151,"Mew",R.drawable.p151,151,"Psíquico","","Dicen que Mew posee el mapa genético de todos los Pokémon. Puede hacerse invisible cuando quiere, así que pasa desapercibido cada vez que se le acerca alguien."));
    }
}
